DAC6-2734: What is the email address for [FI first contact name]
hmrc/crs-fatca-fi-management-frontend pull request #6
Opened 2023-12-08 16:48 UTC by C-Thomp

[DAC6-2734](https://jira.tools.tax.service.gov.uk/browse/DAC6-2734)

2023-12-12 12:24 UTC, C-Thomp commented on app/controllers/FirstContactEmailController.scala
keep seeing this on most files while optimising imports

2023-12-12 13:49 UTC, C-Thomp commented
dynamic name parameter requires name page (DAC6-2733) to exist

2023-12-12 13:50 UTC, C-Thomp commented on README.md
to match prod.routes

2023-12-12 13:51 UTC, C-Thomp commented on app/views/FirstContactEmailView.scala.html
> +@(form: Form[_], mode: Mode, name: String = "[SOME BLOKE]")(implicit request: Request[_], messages: Messages)
the name page is not in the skeleton so DAC6-2733 must be complete before adding this dynamic text

2023-12-14 12:30 UTC, matthewharris1 requested changes

2023-12-14 12:50 UTC, C-Thomp commented on app/forms/FirstContactEmailFormProvider.scala
> +        .verifying(Constraints.emailAddress(errorMessage = "firstContactEmail.error.format"))
ah thats right, that validatedText field mapping didnt exist when i did this -
Constraints are a part of the Play Framework so get all this stuff for free really, you can apply them to a field with the .verifying method 👍

2023-12-15 09:47 UTC, matthewharris1 approved these changes

2023-12-15 09:48 UTC, merged